class Commands {
  static String updateAll() => 'dpkg --configure -a 2>/dev/null; DEBIAN_FRONTEND=noninteractive apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -o Dpkg::Options::=--force-confold && apt-get autoremove -y && apt-get autoclean -y && echo UPDATE COMPLETE';
  static String updatePurgeKernels() => 'dpkg --configure -a 2>/dev/null; DEBIAN_FRONTEND=noninteractive apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -o Dpkg::Options::=--force-confold && apt-get autoremove -y --purge && apt-get autoclean -y && echo UPDATE COMPLETE';
  static String disableAutoUpdates() => 'systemctl stop unattended-upgrades 2>/dev/null; systemctl disable unattended-upgrades 2>/dev/null; systemctl stop apt-daily.timer 2>/dev/null; systemctl disable apt-daily.timer 2>/dev/null; echo DONE';
  static String cleanup() => 'dpkg --configure -a 2>/dev/null; apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y; journalctl --vacuum-time=7d 2>/dev/null; find /tmp -type f -atime +7 -delete 2>/dev/null; echo CLEANUP DONE';
  static String reboot() => 'reboot';
  static String shutdown() => 'shutdown -h now';
  static String hostname() => 'hostname';
  static String checkInternet() => 'ping -c 1 -W 3 8.8.8.8 >/dev/null 2>&1 && echo INTERNET OK || echo NO INTERNET; ping -c 1 -W 3 google.com >/dev/null 2>&1 && echo DNS OK || echo DNS FAIL';
  static String diskUsage() => 'df -h /';
  static String ramInfo() => 'free -h';
  static String uptime() => 'uptime';
  static String services() => 'for s in ssh sshd NetworkManager networking cron crond rsyslog; do status=inactive; systemctl is-active \$s >/dev/null 2>&1 && status=active; if [ \$status = active ]; then echo \$s: ACTIVE; fi; done; echo done';
  static String hardwareInfo() => 'echo --- Hardware ---; dmidecode -s system-manufacturer 2>/dev/null; dmidecode -s system-product-name 2>/dev/null; echo --- CPU ---; grep -m1 "model name" /proc/cpuinfo 2>/dev/null | cut -d: -f2; echo Cores:; nproc 2>/dev/null; echo --- Memory ---; free -h | head -2; echo --- Disk ---; df -h / | tail -1; echo --- OS ---; lsb_release -ds 2>/dev/null || head -1 /etc/os-release 2>/dev/null';
  static String changeDns(String servers) => 'CON=\$(nmcli -t -f NAME,TYPE connection show --active 2>/dev/null | grep ethernet | head -1 | cut -d: -f1); if [ -n "\$CON" ]; then nmcli con mod "\$CON" ipv4.dns "' + servers + '" && nmcli con mod "\$CON" ipv4.ignore-auto-dns yes && nmcli con up "\$CON" 2>/dev/null && echo DNS CHANGED || echo FAILED; else echo NO ETHERNET; fi';
  static String disableWifi() => 'nmcli radio wifi off 2>/dev/null && echo WIFI DISABLED || echo FAILED';
  static String lockScreen() => 'export DISPLAY=:0; xflock4 2>/dev/null || loginctl lock-sessions 2>/dev/null || xdg-screensaver lock 2>/dev/null; echo LOCKED';
  static String sendMessage(String title, String body) => 'echo "#!/bin/bash" > /tmp/_msg.sh; echo "export DISPLAY=:0" >> /tmp/_msg.sh; echo "notify-send \\"' + title + '\\" \\"' + body + '\\" --urgency=critical 2>/dev/null" >> /tmp/_msg.sh; echo "DISPLAY=:0 xmessage -center \\"' + title + ': ' + body + '\\" -timeout 30 2>/dev/null &" >> /tmp/_msg.sh; chmod +x /tmp/_msg.sh; for u in /run/user/*; do uid=\$(basename \$u); user=\$(id -nu \$uid 2>/dev/null); [ -n "\$user" ] && su - \$user -c "bash /tmp/_msg.sh" 2>/dev/null; done; wall "' + title + ': ' + body + '" 2>/dev/null; rm -f /tmp/_msg.sh; echo MESSAGE SENT';
  static String installPackage(String p) => 'dpkg --configure -a 2>/dev/null; DEBIAN_FRONTEND=noninteractive apt-get update -qq && apt-get install -y ' + p + ' && echo INSTALLED || echo FAILED';
  static String installFirefox() => 'dpkg --configure -a 2>/dev/null; apt-get update -qq; apt-get install -y firefox 2>/dev/null || apt-get install -y firefox-esr 2>/dev/null || snap install firefox 2>/dev/null && echo INSTALLED || echo FAILED';
  static String installChrome() => 'dpkg --configure -a 2>/dev/null; wget -q -O /tmp/chrome.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" && dpkg -i /tmp/chrome.deb 2>/dev/null || apt-get install -f -y && rm -f /tmp/chrome.deb && echo INSTALLED || echo FAILED';
  static String removeFirefox() => 'dpkg --configure -a 2>/dev/null; apt-get remove -y firefox firefox-esr 2>/dev/null; snap remove firefox 2>/dev/null; apt-get autoremove -y; echo REMOVED';
  static String removeChrome() => 'dpkg --configure -a 2>/dev/null; apt-get remove -y google-chrome-stable 2>/dev/null; apt-get autoremove -y; echo REMOVED';
  static String fixSlowSudo() => 'HNAME=\$(hostname); grep -q "\$HNAME" /etc/hosts || echo "127.0.1.1 \$HNAME" >> /etc/hosts; echo FIXED';
  static String deleteSSHKeys() => 'rm -f ~/.ssh/known_hosts; echo DONE';
  static String changePassword(String user, String pass) => 'printf "%s:%s" "' + user + '" "' + pass + '" | chpasswd && echo PASSWORD CHANGED || echo FAILED';
  static String speedTest() => 'if ! which speedtest-cli >/dev/null 2>&1; then echo MISSING: speedtest-cli not installed; else speedtest-cli --simple; fi';
  static String fixDpkg() => 'dpkg --configure -a && apt-get install -f -y && echo DPKG FIXED';
  static String fleetSummary() => 'RAM=\$(free -m | grep Mem | tr -s " " | cut -d" " -f2); DISK=\$(df / | tail -1 | tr -s " " | cut -d" " -f5 | tr -d "%"); UPT=\$(cat /proc/uptime | cut -d. -f1); echo "\$RAM|\$DISK|\$UPT"';
}
